apiVersion: apps/v1
kind: Deployment
metadata:
  name: peopleapi
  labels:
    app: peopleapi
spec:
  replicas: 1 # NUMBER_OF_REPLICAS (number of Pods)
  selector:
    matchLabels:
      app: peopleapi
  template:
    metadata:
      labels:
        app: peopleapi
    spec:
      initContainers:
        - name: sqlserver-ready
          image: "mcr.microsoft.com/mssql-tools"
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', '/opt/mssql-tools/bin/sqlcmd -S sqlserver-service,14334 -U sa -P P@ssw0rd123 -Q "SELECT @@VERSION"']
      containers:
      - name: peopleapi
        image: people-api:dev
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE__ENVIRONMENT
          value: Production
        - name: "ConnectionStrings__Default"
          value: "Server=sqlserver-service,14334;Database=K8sPeopleDb;User ID=sa;Password=P@ssw0rd123;MultipleActiveResultSets=true"
        livenessProbe:
          httpGet:
            path: /api/people/ping
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5