apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
spec:
  type: LoadBalancer
  selector:
    # we specify, to which Pods the Service should forward the traffic
    app: k8s-people-db
  ports:
    - name: k8s-people-db-service-port
      port: 14334 # SERVICE_PORT - port exposed by this service
      targetPort: 1433 # Pod's port number (Pod is targeted by the Service)