apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlserver-persistent-volume
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /D/temp
    type: Directory